import { Head, router } from '@inertiajs/react';
import AppLayout from '@/Layouts/AppLayout';
import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from '@/Components/UI/Card';
import { Badge } from '@/Components/UI/Badge';
import { ScrollArea } from '@/Components/UI/ScrollArea';
import { Separator } from '@/Components/UI/Separator';
import { Button } from '@/Components/UI/Button';
import { ArrowLeft, AlertTriangle, CheckCircle, Shield, XCircle, Clock, FileText, Info, Loader2 } from 'lucide-react';
import { useEffect, useState } from 'react';

// Local route helper
const route = (name: string, params?: any) => {
    if (name === 'dashboard') return '/dashboard';
    if (name === 'videos.show') return `/videos/${params}`;
    if (name === 'videos.retry') return `/videos/${params}/retry`;
    if (name === 'videos.cancel') return `/videos/${params}/cancel`;
    return '/';
};

interface Flag {
    timestamp: string;
    category: string;
    severity: string;
    description: string;
}

interface Report {
    safety_score: number;
    summary: string;
    flags: Flag[];
    audio_analysis?: {
        has_speech: boolean;
        language: string;
        summary: string;
        key_phrases: string[];
        suspicious_events: Array<{ timestamp: string; description: string }>;
    };
    error?: string;
    output?: string;
}

interface Video {
    id: number;
    title: string;
    url: string | null;
    status: string;
    report_json: Report | null;
    created_at: string;
    model: string;
}

export default function Show({ video }: { video: Video }) {
    const [progress, setProgress] = useState(0);

    useEffect(() => {
        if (video.status !== 'completed' && video.status !== 'failed') {
            const interval = setInterval(() => {
                router.reload({ only: ['video'] });
            }, 2000); // Poll every 2 seconds

            return () => {
                clearInterval(interval);
            };
        }
    }, [video.status]);

    const getScoreColor = (score: number) => {
        if (score >= 80) return 'text-green-500';
        if (score >= 50) return 'text-yellow-500';
        return 'text-red-500';
    };

    const getScoreGradient = (score: number) => {
        if (score >= 80) return 'from-green-500 to-emerald-700';
        if (score >= 50) return 'from-yellow-500 to-orange-600';
        return 'from-red-500 to-rose-700';
    };

    const getSeverityBadge = (severity: string) => {
        const sev = severity.toLowerCase();
        if (sev === 'high') return <Badge variant="destructive" className="uppercase text-[10px] tracking-wider">High Risk</Badge>;
        if (sev === 'medium') return <Badge variant="secondary" className="bg-yellow-500/15 text-yellow-600 dark:text-yellow-400 hover:bg-yellow-500/25 uppercase text-[10px] tracking-wider border-yellow-500/20">Medium Risk</Badge>;
        return <Badge variant="outline" className="text-muted-foreground uppercase text-[10px] tracking-wider">Low Risk</Badge>;
    };

    return (
        <AppLayout breadcrumbs={[
            { title: 'Dashboard', href: route('dashboard') },
            { title: 'Analysis Result', href: '' }
        ]}>
            <Head>
                <title>{`Analysis: ${video.title} - Checkvid`}</title>
                <meta name="description" content={`Safety analysis report for "${video.title}". Score: ${video.report_json?.safety_score || 'N/A'}/100. Generated by Checkvid.`} />
                <link rel="canonical" href={`https://checkvid.app/videos/${video.id}`} />

                {/* Open Graph */}
                <meta property="og:type" content="article" />
                <meta property="og:url" content={`https://checkvid.app/videos/${video.id}`} />
                <meta property="og:title" content={`Safety Analysis: ${video.title}`} />
                <meta property="og:description" content={`Checkvid analysis score: ${video.report_json?.safety_score || 'N/A'}/100. ${video.report_json?.summary?.substring(0, 150)}...`} />
                <meta property="og:image" content="https://checkvid.app/og-image.jpg" />
                <meta property="og:site_name" content="Checkvid" />

                {/* Twitter */}
                <meta name="twitter:card" content="summary_large_image" />
                <meta name="twitter:title" content={`Safety Analysis: ${video.title}`} />
                <meta name="twitter:description" content={`Checkvid analysis score: ${video.report_json?.safety_score || 'N/A'}/100. ${video.report_json?.summary?.substring(0, 150)}...`} />
                <meta name="twitter:image" content="https://checkvid.app/og-image.jpg" />

                {/* Structured Data (JSON-LD) */}
                <script type="application/ld+json">
                    {JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "Report",
                        "headline": `Safety Analysis: ${video.title}`,
                        "description": video.report_json?.summary || "Video safety analysis report.",
                        "datePublished": video.created_at,
                        "author": {
                            "@type": "Organization",
                            "name": "Checkvid"
                        },
                        "about": {
                            "@type": "VideoObject",
                            "name": video.title,
                            "uploadDate": video.created_at,
                            "contentUrl": video.url || ""
                        },
                        "aggregateRating": {
                            "@type": "AggregateRating",
                            "ratingValue": video.report_json?.safety_score,
                            "bestRating": "100",
                            "worstRating": "0",
                            "ratingCount": "1"
                        }
                    })}
                </script>
            </Head>

            <div className="flex flex-col gap-8 p-6 md:p-10 max-w-7xl mx-auto w-full animate-in fade-in slide-in-from-bottom-4 duration-500">

                {/* Header */}
                <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4 border-b border-border/40 pb-6">
                    <div className="space-y-1">
                        <div className="flex items-center gap-2 text-muted-foreground text-sm mb-2">
                            <Button variant="ghost" size="sm" className="-ml-3 h-8 text-muted-foreground hover:text-foreground" onClick={() => window.history.back()}>
                                <ArrowLeft className="w-4 h-4 mr-1" /> Back
                            </Button>
                            <Separator orientation="vertical" className="h-4" />
                            <span className="font-mono text-xs">{new Date(video.created_at).toLocaleString()}</span>
                            <Separator orientation="vertical" className="h-4" />
                            <span className="font-mono text-xs">{video.model}</span>
                        </div>
                        <h1 className="text-3xl font-bold tracking-tight">{video.title || 'Untitled Analysis'}</h1>
                        <p className="text-muted-foreground max-w-2xl text-sm truncate">{video.url || 'Uploaded Video'}</p>
                    </div>

                    <div className={`px-4 py-1.5 rounded-full border flex items-center gap-2 font-medium shadow-sm ${video.status === 'completed' ? 'bg-green-500/10 border-green-500/20 text-green-600 dark:text-green-400' :
                        (video.status === 'failed' ? 'bg-red-500/10 border-red-500/20 text-red-600 dark:text-red-400' :
                            'bg-blue-500/10 border-blue-500/20 text-blue-600 dark:text-blue-400')
                        }`}>
                        {video.status === 'completed' && <CheckCircle className="w-4 h-4" />}
                        {video.status === 'failed' && <XCircle className="w-4 h-4" />}
                        {video.status === 'processing' && <Loader2 className="w-4 h-4 animate-spin" />}
                        <span className="capitalize">{video.status}</span>
                    </div>
                </div>

                {video.status !== 'completed' && video.status !== 'failed' && video.status !== 'stopped' && (
                    <Card className="border-0 shadow-2xl bg-card/50 backdrop-blur-xl ring-1 ring-white/10 relative overflow-hidden">
                        <div className="absolute top-0 left-0 w-full h-1 bg-muted">
                            <div className="h-full bg-primary transition-all duration-1000 ease-out" style={{
                                width: `${video.status.toLowerCase().includes('downloading') ? 20 :
                                    video.status.toLowerCase().includes('uploading') ? 45 :
                                        video.status.toLowerCase().includes('processing') ? 70 :
                                            video.status.toLowerCase().includes('analyzing') ? 85 :
                                                video.status.toLowerCase().includes('generating') ? 95 : 5
                                    }%`
                            }}></div>
                        </div>
                        <CardContent className="py-16 text-center flex flex-col items-center justify-center space-y-6">
                            <div className="relative">
                                <div className="absolute inset-0 bg-primary/20 blur-2xl rounded-full animate-pulse"></div>
                                <div className="relative bg-background rounded-full p-6 shadow-xl border border-border/50">
                                    <Loader2 className="w-12 h-12 animate-spin text-primary" />
                                </div>
                            </div>
                            <div className="space-y-4 max-w-lg w-full">
                                <div className="space-y-1">
                                    <h3 className="text-xl font-semibold animate-pulse">{video.status}...</h3>
                                    <p className="text-muted-foreground text-sm">Please wait while our AI analyzes your content.</p>

                                    {/* Stuck Detection Hint */}
                                    {(new Date().getTime() - new Date(video.created_at).getTime()) > 120000 && (
                                        <div className="mt-4 p-3 bg-yellow-500/10 border border-yellow-500/20 rounded-md text-yellow-600 dark:text-yellow-400 text-xs">
                                            <p className="font-semibold flex items-center justify-center gap-2">
                                                <AlertTriangle className="w-3 h-3" />
                                                Taking longer than usual?
                                            </p>
                                            <p className="mt-1">
                                                Complex videos can take up to 5 minutes. If it stays stuck, you can
                                                <button onClick={() => router.post(route('videos.retry', video.id))} className="underline ml-1 hover:text-yellow-500 font-bold">Restart Analysis</button>.
                                            </p>
                                        </div>
                                    )}
                                </div>



                                <div className="pt-4">
                                    <Button
                                        variant="destructive"
                                        size="sm"
                                        onClick={() => router.post(route('videos.cancel', video.id))}
                                        className="gap-2"
                                    >
                                        <XCircle className="w-4 h-4" /> Stop Analysis
                                    </Button>
                                </div>
                            </div>
                        </CardContent>
                    </Card>
                )}

                {(video.status === 'failed' || video.status === 'stopped') && (
                    <Card className="border-destructive/50 shadow-lg bg-destructive/5">
                        <CardHeader>
                            <div className="flex items-center gap-3 text-destructive">
                                <AlertTriangle className="w-6 h-6" />
                                <CardTitle>Analysis {video.status === 'stopped' ? 'Stopped' : 'Failed'}</CardTitle>
                            </div>
                        </CardHeader>
                        <CardContent className="space-y-4">
                            <p className="font-medium text-foreground">{video.report_json?.error || 'An unexpected error occurred.'}</p>
                            {video.report_json?.output && (
                                <div className="rounded-md border border-destructive/20 bg-background/50 p-4">
                                    <pre className="text-xs text-muted-foreground whitespace-pre-wrap font-mono overflow-auto max-h-[300px]">
                                        {video.report_json.output}
                                    </pre>
                                </div>
                            )}
                        </CardContent>
                        <CardFooter className="gap-4">
                            <Button
                                onClick={() => router.post(route('videos.retry', video.id))}
                                className="gap-2"
                            >
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 12a9 9 0 0 1 9-9 9.75 9.75 0 0 1 6.74 2.74L21 8" /><path d="M21 3v5h-5" /><path d="M21 12a9 9 0 0 1-9 9 9.75 9.75 0 0 1-6.74-2.74L3 16" /><path d="M8 16H3v5" /></svg>
                                Try Again
                            </Button>
                        </CardFooter>
                    </Card>
                )}

                {video.status === 'completed' && video.report_json && (
                    <div className="grid lg:grid-cols-12 gap-8">

                        {/* Sidebar: Score & Summary (4 cols) */}
                        <div className="lg:col-span-4 space-y-6">
                            {/* Safety Score Card */}
                            <Card className="overflow-hidden border-0 shadow-xl bg-card/50 backdrop-blur-xl ring-1 ring-white/10">
                                <CardHeader className="pb-2">
                                    <CardTitle className="flex items-center gap-2">
                                        <Shield className="w-5 h-5 text-primary" /> Safety Score
                                    </CardTitle>
                                </CardHeader>
                                <CardContent className="flex flex-col items-center justify-center py-8">
                                    <div className="relative w-48 h-48 flex items-center justify-center">
                                        {/* Circular Progress Background */}
                                        <svg className="w-full h-full transform -rotate-90" viewBox="0 0 100 100">
                                            <circle cx="50" cy="50" r="45" fill="none" stroke="currentColor" strokeWidth="8" className="text-muted/20" />
                                            {/* Actual Progress */}
                                            <circle
                                                cx="50"
                                                cy="50"
                                                r="45"
                                                fill="none"
                                                stroke="currentColor"
                                                strokeWidth="8"
                                                strokeDasharray="283"
                                                strokeDashoffset={283 - (283 * video.report_json.safety_score) / 100}
                                                strokeLinecap="round"
                                                className={`transition-all duration-1000 ease-out ${getScoreColor(video.report_json.safety_score)}`}
                                            />
                                        </svg>
                                        <div className="absolute inset-0 flex flex-col items-center justify-center">
                                            <span className={`text-5xl font-black tracking-tighter ${getScoreColor(video.report_json.safety_score)}`}>
                                                {video.report_json.safety_score}
                                            </span>
                                            <span className="text-xs uppercase tracking-widest text-muted-foreground font-medium mt-1">out of 100</span>
                                        </div>
                                    </div>

                                    <div className="mt-6 text-center px-4">
                                        <div className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-medium border ${video.report_json.safety_score >= 80 ? 'bg-green-500/10 text-green-600 border-green-500/20' :
                                            (video.report_json.safety_score >= 50 ? 'bg-yellow-500/10 text-yellow-600 border-yellow-500/20' : 'bg-red-500/10 text-red-600 border-red-500/20')
                                            }`}>
                                            {video.report_json.safety_score >= 80 ? 'Safe Content' : (video.report_json.safety_score >= 50 ? 'Moderate Concern' : 'High Risk Content')}
                                        </div>
                                    </div>
                                </CardContent>
                            </Card>

                            {/* Executive Summary */}
                            <Card className="border-border/50 bg-card/30">
                                <CardHeader>
                                    <CardTitle className="flex items-center gap-2 text-base">
                                        <FileText className="w-4 h-4 text-muted-foreground" /> Executive Summary: {video.title}
                                    </CardTitle>
                                </CardHeader>
                                <CardContent>
                                    <p className="text-sm leading-relaxed text-muted-foreground mb-4">
                                        {video.report_json.summary}
                                    </p>
                                    {video.url && (
                                        <div className="pt-4 border-t border-border/50">
                                            <p className="text-xs font-medium text-muted-foreground mb-1">Video Source</p>
                                            <a
                                                href={video.url}
                                                target="_blank"
                                                rel="noopener noreferrer"
                                                className="text-sm text-primary hover:underline break-all flex items-center gap-1"
                                            >
                                                {video.url}
                                            </a>
                                        </div>
                                    )}
                                </CardContent>
                            </Card>
                        </div>

                        {/* Main Content: Flags (8 cols) */}
                        <div className="lg:col-span-8 flex flex-col gap-8">
                            {/* Audio Analysis Section */}
                            {video.report_json.audio_analysis && (
                                <Card className="border-0 shadow-lg bg-card/50 backdrop-blur-sm ring-1 ring-white/10">
                                    <CardHeader>
                                        <div className="flex items-center justify-between">
                                            <CardTitle className="flex items-center gap-2">
                                                <div className="p-1.5 bg-blue-500/10 rounded-md">
                                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-blue-500"><path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" /><path d="M19 10v2a7 7 0 0 1-14 0v-2" /><line x1="12" x2="12" y1="19" y2="22" /></svg>
                                                </div>
                                                Audio Intelligence
                                            </CardTitle>
                                            <Badge variant={video.report_json.audio_analysis.has_speech ? "default" : "secondary"}>
                                                {video.report_json.audio_analysis.has_speech ? "Speech Detected" : "No Speech"}
                                            </Badge>
                                        </div>
                                    </CardHeader>
                                    <CardContent className="space-y-6">
                                        <div className="grid md:grid-cols-2 gap-6">
                                            <div className="space-y-4">
                                                <div>
                                                    <h4 className="text-sm font-medium text-muted-foreground mb-1 uppercase tracking-wider text-[10px]">Audio Summary</h4>
                                                    <p className="text-sm leading-relaxed">{video.report_json.audio_analysis.summary}</p>
                                                </div>
                                                <div>
                                                    <h4 className="text-sm font-medium text-muted-foreground mb-2 uppercase tracking-wider text-[10px]">Key Phrases</h4>
                                                    <div className="flex flex-wrap gap-2">
                                                        {video.report_json.audio_analysis.key_phrases?.length > 0 ? (
                                                            video.report_json.audio_analysis.key_phrases.map((phrase, i) => (
                                                                <span key={i} className="px-2.5 py-1 rounded-md bg-secondary/50 border border-border text-xs font-medium text-secondary-foreground">
                                                                    "{phrase}"
                                                                </span>
                                                            ))
                                                        ) : <span className="text-xs text-muted-foreground italic">No key phrases extracted</span>}
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="space-y-4">
                                                <div>
                                                    <h4 className="text-sm font-medium text-muted-foreground mb-2 uppercase tracking-wider text-[10px]">Suspicious Audio Events</h4>
                                                    {video.report_json.audio_analysis.suspicious_events?.length > 0 ? (
                                                        <div className="space-y-2">
                                                            {video.report_json.audio_analysis.suspicious_events.map((event, i) => (
                                                                <div key={i} className="flex items-center gap-3 p-2 rounded-lg bg-red-500/5 border border-red-500/10">
                                                                    <Badge variant="outline" className="font-mono text-[10px] h-5 border-red-200 text-red-700 bg-red-50 dark:bg-red-950/30 dark:border-red-900 dark:text-red-400">
                                                                        {event.timestamp}
                                                                    </Badge>
                                                                    <span className="text-sm font-medium text-red-600 dark:text-red-400">{event.description}</span>
                                                                </div>
                                                            ))}
                                                        </div>
                                                    ) : (
                                                        <div className="flex items-center gap-2 p-3 rounded-lg bg-green-500/5 border border-green-500/10 text-green-600 dark:text-green-400">
                                                            <CheckCircle className="w-4 h-4" />
                                                            <span className="text-sm font-medium">No suspicious audio detected</span>
                                                        </div>
                                                    )}
                                                </div>
                                                <div className="flex items-center justify-between text-xs pt-4 border-t border-border/30">
                                                    <span className="text-muted-foreground">Language Detected:</span>
                                                    <span className="font-mono font-medium">{video.report_json.audio_analysis.language || 'Unknown'}</span>
                                                </div>
                                            </div>
                                        </div>
                                    </CardContent>
                                </Card>
                            )}
                            <Card className="h-full border-0 shadow-xl bg-card/50 backdrop-blur-xl ring-1 ring-white/10">
                                <CardHeader>
                                    <div className="flex items-center justify-between">
                                        <CardTitle className="flex items-center gap-2">
                                            <AlertTriangle className="w-5 h-5 text-primary" /> Detected Flags
                                        </CardTitle>
                                        <Badge variant="outline" className="ml-auto">
                                            {video.report_json.flags?.length || 0} issues found
                                        </Badge>
                                    </div>
                                    <CardDescription>Chronological timeline of potential safety violations.</CardDescription>
                                </CardHeader>
                                <Separator />
                                <CardContent className="p-0">
                                    <ScrollArea className="h-[600px] w-full p-6">
                                        {video.report_json.flags && video.report_json.flags.length > 0 ? (
                                            <div className="relative border-l border-border/50 ml-3 space-y-8 pl-8 py-2">
                                                {video.report_json.flags.map((flag, index) => (
                                                    <div key={index} className="relative group">
                                                        {/* Timeline Dot */}
                                                        <div className="absolute -left-[39px] top-1 p-1 bg-background rounded-full border border-border group-hover:border-primary transition-colors">
                                                            <div className="w-2 h-2 rounded-full bg-muted-foreground group-hover:bg-primary transition-colors"></div>
                                                        </div>

                                                        {/* Content */}
                                                        <div className="flex flex-col sm:flex-row gap-4 p-4 rounded-xl bg-muted/20 border border-transparent hover:border-primary/20 hover:bg-muted/40 transition-all duration-300">
                                                            <div className="shrink-0 flex sm:flex-col items-center gap-2 sm:w-24">
                                                                <Badge variant="outline" className="font-mono text-xs flex gap-1 items-center">
                                                                    <Clock className="w-3 h-3" /> {flag.timestamp}
                                                                </Badge>
                                                            </div>
                                                            <div className="space-y-2 flex-1">
                                                                <div className="flex items-center gap-2 flex-wrap">
                                                                    <span className="font-semibold text-sm">{flag.category}</span>
                                                                    {getSeverityBadge(flag.severity)}
                                                                </div>
                                                                <p className="text-sm text-muted-foreground leading-snug">
                                                                    {flag.description}
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                        ) : (
                                            <div className="flex flex-col items-center justify-center py-20 text-center space-y-4">
                                                <div className="p-4 bg-green-500/10 rounded-full text-green-500">
                                                    <CheckCircle className="w-12 h-12" />
                                                </div>
                                                <div>
                                                    <h3 className="text-lg font-medium">No Flags Detected</h3>
                                                    <p className="text-muted-foreground max-w-xs mx-auto mt-1">The AI did not find any content violations in this video.</p>
                                                </div>
                                            </div>
                                        )}
                                    </ScrollArea>
                                </CardContent>
                            </Card>
                        </div>
                    </div>
                )}
            </div>
        </AppLayout>
    );
}
